export const brandColors = {
  primary: "#640023",
  primaryContainer: "#881337",
  onPrimary: "#ffffff",
  onPrimaryContainer: "#ff93a6",
  primaryFixed: "#ffd9dd",
  primaryFixedDim: "#ffb2bd",
  secondary: "#006d30",
  secondaryContainer: "#92f5a4",
  onSecondary: "#ffffff",
  onSecondaryContainer: "#007233",
  tertiary: "#512100",
  tertiaryContainer: "#743200",
  onTertiary: "#ffffff",
  onTertiaryContainer: "#ff9a5e",
  background: "#fff8f5",
  onBackground: "#1e1b19",
  surface: "#fff8f5",
  surfaceBright: "#fff8f5",
  surfaceDim: "#e0d8d5",
  surfaceContainerLowest: "#ffffff",
  surfaceContainerLow: "#faf2ee",
  surfaceContainer: "#f4ece8",
  surfaceContainerHigh: "#eee7e3",
  surfaceContainerHighest: "#e9e1dd",
  surfaceVariant: "#e9e1dd",
  onSurface: "#1e1b19",
  onSurfaceVariant: "#574144",
  outline: "#8a7174",
  outlineVariant: "#debfc2",
  inverseSurface: "#33302d",
  inverseOnSurface: "#f7efeb",
  inversePrimary: "#ffb2bd",
  error: "#ba1a1a",
  onError: "#ffffff",
  errorContainer: "#ffdad6",
  onErrorContainer: "#93000a",
  pureVeg: "#15803d",
  surfaceTint: "#aa304f",
} as const;

export const brandFonts = {
  display: "Playfair Display",
  body: "Plus Jakarta Sans",
} as const;

export const layoutTokens = {
  maxWidth: "1720px",
  margin: "3rem",
  marginMobile: "1rem",
  gutter: "1.5rem",
} as const;
